### ISSUE TITLE
Could not get unknown property 'FLIPPER_VERSION'

### ISSUE THREAD

**Issue by Bohmaster** [jk-gan/redux-flipper#15]
I've followed the installation steps and got this error:

> FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rtrovant/surhive/Umir/node_modules/react-native-flipper/android/build.gradle' line: 86

* What went wrong:
A problem occurred evaluating project ':react-native-flipper'.
> Could not get unknown property 'FLIPPER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

This is my code:

`import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

import reducers from './reducers';

export default configureStore = () => {
    let store;

    if (__DEV__) {
        const createDebugger = require('redux-flipper').default;
        store = createStore(
            reducers,
            {}, 
            applyMiddleware(createDebugger, thunk)
        );
    } else {
        store = createStore(
            reducers,
            {}, 
        );
    }
    
    return store;
};
`
RN version: 0.62.2
Flipper version: 0.37.0

**Comment by plwai** [comment]
Is your app upgraded from RN version lesser than 0.62.0 manually? 

Flipper will only be enabled by default if the application template is newly created by RN version starting 0.62.0 or upgraded by using an upgrade tool.

Below is the steps for manual upgrade:
https://fbflipper.com/docs/getting-started/react-native

If you are doing the upgrade manually, you need to add the setting below into `android > grandle.properties` as well

FLIPPER_VERSION=0.37.0

**Comment by jk-gan** [comment]
I think we can close this issue due to a long lack of response from the author.

**Comment by Dharmi201** [comment]
Faced this issue while trying to upgrade manually from 0.61.4 to 0.63.3 
Got it to work by making changes in android/app/build.gradle 
Replaced ${FlIPPER_VERSION} with 0.35.0 
`debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
	   exclude group:'com.facebook.fbjni'
  }
	
 debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
     exclude group:'com.facebook.flipper'
     exclude group:'com.squareup.okhttp3', module:'okhttp'
 }
debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
    exclude group:'com.facebook.flipper'
}`  
Let me know if there is another, better or more effective workaround for long term keeping future react-native updates in mind.
