### ISSUE TITLE
error with actionBlacklist - Promise Rejection: cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by andresouza** [jk-gan/redux-flipper#24]
**Repro Steps:**
Call `createDebugger` with a empty object `{}` or just `{ resolveCyclic }`. Example:
`createDebugger({ resolveCyclic: true })`

**Current Behaviour**
The `defaultConfig` is ignored and the parameter `actionsBlacklist` is `undefined`, causing a crash in this line:
`if (actionsBlacklist.length) {`

**Expected Behaviour**
`actionsBlacklist` should be `[]` by default if not provided

**Notes**
One way  to circumvent this problem would be to always provide both options like this:
`createDebugger({ resolveCyclic: true, actionsBlacklist: [] })`
But this isn't ideal because I believe that both parameters are optional, right?

**Comment by plwai** [comment]
Thanks for reporting this. A patch will be release asap.

**Comment by plwai** [comment]
Fixed in V1.3.1
