### ISSUE TITLE
Slow when dealing with a big state tree

### ISSUE THREAD

**Issue by lukemcgregor** [jk-gan/redux-flipper#27]
I have a really large state tree (5mb + of JSON uncompressed). In the app itself its pretty quick to deal with and i dont have any performance issues but when i turn on redux-flipper, (also using flipper-plugin-redux-debug), the app is very slow and uses a lot of CPU. 

As this is the app using CPU (not flipper) I think whatever the issue is exists in this library.

**Comment by plwai** [comment]
Did you enable any optional feature? It would be great if you can provide the `createDebugger` code segment.

**Comment by lukemcgregor** [comment]
Hey, thanks for the fast response. Ive tried two things:
```
if (__DEV__) {
  const createDebugger = require('redux-flipper').default;
  middleware.push(createDebugger());
}
```

and also with a blacklist on the biggest event I use. 

```
if (__DEV__) {
  const createDebugger = require('redux-flipper').default;
  middleware.push(createDebugger({ actionsBlackList: ['BIG_ACTION']}));
}
```

**Comment by plwai** [comment]
I have looked into the flipper library and got the same findings as well. The performance bottleneck is at the process of parsing JSON [here](https://github.com/facebook/flipper/blob/9ada27526c32ee7e53e4ee5bf7da54d6abff2006/react-native/react-native-flipper/android/src/debug/java/com/facebook/flipper/reactnative/FlipperReactNativeJavaScriptPluginManager.java#L93). MIght need to open an issue in flipper side.

**Comment by henrikra** [comment]
@lukemcgregor Docs are wrong about `actionsBlacklist` https://github.com/jk-gan/redux-flipper/issues/32

**Comment by ovidiu-balau** [comment]
Is there any update on this? Even when only whitelisting a small part of the app, actions are still lagging behind real-time.
