### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by felippepuhle** [jk-gan/redux-flipper#28]
Is there a reason we need to run `yarn add react-native-flipper`?

I've spent some time on [this issue](https://github.com/facebook/flipper/issues/648) after updating Flipper to `0.51.0` and just figured out that's the cause.

I just removed from my `package.json` and the plugin is still working.

Thanks!

**Comment by jk-gan** [comment]
Hi, we are following Flipper documentation [here](https://fbflipper.com/docs/tutorial/react-native/) where it say: 
> To expose Flipper to the JavaScript world, the React Native Native Module `react-native-flipper` needs to be installed in the hosting application by running `yarn add react-native-flipper` and `cd ios && pod install`. If you are developing a plugin that is distributed as NPM package, make sure to add this to the installation instruction of your package as well!

**Comment by felippepuhle** [comment]
Oh I see! Thanks for the update!

I'll close this issue then, I've decided to open just in case anyone gets the same error.
