### ISSUE TITLE
Can't Toggle Details on Flipper / Can't see debug tree

### ISSUE THREAD

**Issue by ErickMaeda** [jk-gan/redux-flipper#29]
I'm trying to debug the reducers tree, but not able.

My package.json
```
{
        "react": "16.13.1",
        "react-native": "0.63.2",
        "react-native-flipper": "^0.45.0",
        "redux-flipper": "^1.2.0",
}
```

I'm using flipper version 0.54.0 on MacOS

Here is the attach that you can see.
<img width="1674" alt="Screenshot 2020-09-01 at 00 10 49" src="https://user-images.githubusercontent.com/12499837/91777559-170eb000-ebe8-11ea-9a6c-b3d4107c67dc.png">

**Comment by ErickMaeda** [comment]
Closing this, as it is not a bug. Just a user trying to use Flipper. lol

To solve this.

-> Click on any action dispatched. 
-> You can now see the detail. 

<img width="1680" alt="Screenshot 2020-09-01 at 10 52 52" src="https://user-images.githubusercontent.com/12499837/91835710-a6947d00-ec41-11ea-9a22-0a2803cefbe4.png">

**Comment by gabrielmoncea** [comment]
@ErickMaeda @jk-gan this issue should be opened back. I'm selecting an action type but still cannot see the state window
