### ISSUE TITLE
Typo in docs on actionsBlacklist

### ISSUE THREAD

**Issue by henrikra** [jk-gan/redux-flipper#32]
In the docs it says `actionsBlackList` but the real one is `actionsBlacklist`

**Comment by plwai** [comment]
@henrikra good catch! We will update it in no time. It will be great if you can create the PR for it too.

**Comment by henrikra** [comment]
@plwai I can maybe create PR for that later but I made more crucial PR here https://github.com/jk-gan/redux-flipper/pull/33 Can you check it out?

**Comment by plwai** [comment]
fixed in v1.4.0
