### ISSUE TITLE
resolveCyclic alternative

### ISSUE THREAD

**Issue by wilau2** [jk-gan/redux-flipper#34]
We have been using `react-native-debugger` before flipper and the redux-flipper plugin and the behavior is a bit different for the equivalent of the `resolveCyclic` option. 

Instead of including optionally `cycle.js` they are using [jsan](https://github.com/kolodny/jsan) and replace the problematic cyclical structure by the `"[CIRCULAR]"` keyword in the json objects.

Here is the proposed [solution](https://github.com/zalmoxisus/redux-devtools-extension/blob/c220fd18d6fb4b0790a501ec4df0de52b5bee460/src/app/api/index.js#L26)

You will end up by having some "modified" payloads logged for the different actions but at least you would see the `action.type` instead of an error. 

I could go ahead and draft a PR if the maintainers of this repo are interested in that solution.

**Comment by plwai** [comment]
There was a PR #23 about this issue but we could not figure out which action attribute is in cyclic. Now I can see the cyclic part is in the action payload. We will resolve and merge that PR shortly.

**Comment by plwai** [comment]
close as resolved.

**Comment by felippepuhle** [comment]
`cycle.js` also does not have a license which is causing some problems here, would you accept a PR changing it as suggested on this issue @jk-gan @plwai? Thanks!
