### ISSUE TITLE
Is the time presented in the redux-debugger reliable?

### ISSUE THREAD

**Issue by marqroldan** [jk-gan/redux-flipper#35]
This is probably just my lack of experience with Redux but it's making me doubt the amount of time an action takes because even if I just return the original state, it still takes around 350-400ms average.

I haven't checked any other debugger for redux, I'm currently using this in react-native.

**Comment by plwai** [comment]
This is because your state tree is too big to be parsed in the flipper native send API. ( #27 for more details).

Currently, the only solution is reducing the size by using blacklist and whitelist features.

**Comment by marqroldan** [comment]
Hey, that was fast!

And I found out about the other issues just now, apologies for not looking further.
Thanks!
