### ISSUE TITLE
Support react-navigation devtools

### ISSUE THREAD

**Issue by christophemenager** [jk-gan/redux-flipper#38]
Hi there ! Thanks a lot for this plugin 👍 

This issue is just a suggestion of a new feature that would be amazing :) 

react navigation provides a great debugging tool that is integrated with redux-devtools but does not work with your plugin :/
https://reactnavigation.org/docs/devtools/

Do you think that would be easy to fix ?

**Comment by jk-gan** [comment]
Hi, sorry for the late reply. I will try to look at it on this weekend. Will update you if I find a way to implement this.

**Comment by jakobo** [comment]
Just a note: There's now a flipper plugin available in React Navigation that may be more ideal. This way every Flipper plugin can keep its scope small. https://reactnavigation.org/docs/6.x/devtools/#useflipper
