### ISSUE TITLE
dependency react-native-flipper@"^0.63.0"

### ISSUE THREAD

**Issue by voxspox** [jk-gan/redux-flipper#40]
Currently `redux-flipper@1.4.2` requires `react-native-flipper@"^0.63.0"` but the current version of Flipper is already 0.84

Is there a way to upgrade Flipper.

**Comment by jk-gan** [comment]
Hi, I think we can update the dependecies. Do you want to make a PR for this?

**Comment by voxspox** [comment]
hmm, I think a fixed dep is not good because it depends which Flipper version is actually used by the developer...

May this issue could be fixed by using a [peer-dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) instead.

**Comment by eightyfive** [comment]
Trying to setup with RN 0.64.0 and Flipper 0.85 I get the following Flipper error message in Mac client:

> Redux Debugger (flipper-plugin-redux-debugger@1.2.1): Plugin 'Redux Debugger' is not supported by the client application

Not sure what needs to be done ! Is it a simple dependency issue or does the plugin not work with the latest versions of both RN & Flipper ?

Let us know and I can make a PR.

**Comment by plwai** [comment]
> Trying to setup with RN 0.64.0 and Flipper 0.85 I get the following Flipper error message in Mac client:
> 
> > Redux Debugger (flipper-plugin-redux-debugger@1.2.1): Plugin 'Redux Debugger' is not supported by the client application
> 
> Not sure what needs to be done ! Is it a simple dependency issue or does the plugin not work with the latest versions of both RN & Flipper ?
> 
> Let us know and I can make a PR.

Could you provide more details? 
I tried to run RN 0.64.0 and Flipper 0.85. It is working fine.

**Comment by eightyfive** [comment]
My bad, it works as expected.

I just forgot the to append `.default` when requiring the module:
```js
if (__DEV__) {
  const devConfig = require('./store.dev').default;

  merge(config, devConfig);
}
```
