### ISSUE TITLE
Cannot find the Redux Debugger tab

### ISSUE THREAD

**Issue by ghasemikasra39** [jk-gan/redux-flipper#48]
```Javascript 
import {configureStore} from '@reduxjs/toolkit'
import counterSlice from "./reducers/counterSlice";

let middleware = [];

if (__DEV__) {
  const createDebugger = require('redux-flipper').default;
  middleware.push(createDebugger());
}

export const store = configureStore({
  reducer: {
    counter: counterSlice
  },
  middleware
})
```

![Screenshot 2021-07-07 at 15 27 35](https://user-images.githubusercontent.com/24314029/124767488-26f9cd80-df38-11eb-9cd1-2efa5ea85077.png)
![Screenshot 2021-07-07 at 15 28 17](https://user-images.githubusercontent.com/24314029/124767504-29f4be00-df38-11eb-93d7-eb2d42ac89b0.png)

```json
"react-native-flipper": "^0.96.1"
"redux-flipper": "^1.4.2"
"react-native": "0.64.1"
```

environment:
```bash
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 66.96 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/Documents/realnote_app/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
```

**Comment by plwai** [comment]
@ghasemikasra39 According to your screenshot, your application is not selected. Redux debugger would only show after you connect an application.

**Comment by ghasemikasra39** [comment]
@plwai 
If my application is not selected, then why I can see my my log appearing?!!

![Screenshot 2021-07-08 at 19 20 37](https://user-images.githubusercontent.com/24314029/124964909-d65e9f00-e021-11eb-8b47-1460948150d3.png)

**Comment by plwai** [comment]
@ghasemikasra39 
That only show you started react native. You need to run your application either in emulator or in your phone. In your screenshot, flipper clearly show you that **NO APPLICATION SELECTED**. If you do it correctly, you should able to see something like this.

![image](https://user-images.githubusercontent.com/9108726/124968324-07f25d00-e058-11eb-8490-72c24c6e3597.png)

**Comment by ghasemikasra39** [comment]
@plwai 
I can confirm that my app is fully running on my simulator, and I can see my logs, error, warnings in the log section. Am I missing something?
![Screenshot 2021-07-08 at 23 11 18](https://user-images.githubusercontent.com/24314029/124991530-12096100-e042-11eb-8943-ffa6163c11b2.png)

**Comment by jk-gan** [comment]
Can u try [this](https://fbflipper.com/docs/troubleshooting#q-i-see-my-app-but-i-dont-see-the-external-plugins-ive-installed) to check if this helps?

**Comment by ghasemikasra39** [comment]
> Can u try [this](https://fbflipper.com/docs/troubleshooting#q-i-see-my-app-but-i-dont-see-the-external-plugins-ive-installed) to see if this helps?

Sure, I will try this and will let you know.

**Comment by ghasemikasra39** [comment]
Dear @jk-gan 
I tested the library on a brand new RN project and worked perfectly fine. There must be some other issue with my own project. So I close this issue.
