### ISSUE TITLE
Android: The native module for Flipper seems unavailable + No redux log in flipper desktop

### ISSUE THREAD

**Issue by MohammadAzimi** [jk-gan/redux-flipper#53]
I'm using redux-toolkit + redux-persist
```js
react-native: 0.63.4,
react-native-flipper: 0.104.0
redux-flipper: 2.0.0,
```
android/app/gradle
```groovy
    //FLIPPER_VERSION = 0.104.0
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
```
This is my **store** config
```js
const persistConfig = {
  key: 'root-luna',
  version: 1,
  storage: AsyncStorage,
  whitelist: ['userState'],
};

const persistedReducer = persistReducer(persistConfig, rootReducer);
const middlewares = [];

if (__DEV__) {
  const createDebugger = require('redux-flipper').default;
  middlewares.push(createDebugger());
}

export const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
    }).concat(middlewares),
  devTools: __DEV__,
  // preloadedState,
  // enhancers: [reduxBatch],
});
export const persistor = persistStore(store);
```
I wanted to see redux logs in flipper so I add **redux-flipper** to my project. and flipper-plugin-redux-debugger
2.0.0 in flipper desktop (windows) and the status color is green. Then I received errors about missing **react-native-flipper**; so I installed it too. 
But now I'm having 2 issues:
- The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory. _(I didn't have this warning before and I'm running my app on an android device. I've also had tried ./gradlew clean and rebuilding my project)_
- NO REDUX LOG is visible in log section of flipper!

**Comment by plwai** [comment]
@MohammadAzimi Does flipper able to connect to your application?

**Comment by MohammadAzimi** [comment]
@plwai yes it does

**Comment by plwai** [comment]
Did you try this?
https://github.com/facebook/flipper/issues/1253

**Comment by MohammadAzimi** [comment]
https://github.com/facebook/flipper/issues/1253#issuecomment-663423999
This one helped me. I had changed android package name 🤦‍♂️
