### ISSUE TITLE
Bug when running redux-debugger on Flipper

### ISSUE THREAD

**Issue by Isaacmeedinaa** [jk-gan/redux-flipper#62]
I receive an `Uncaught Error` when running redux-debugger plugin for my RN app.

Screen shot of the error:
[https://imgur.com/O6I1Fcr](url)

Block of code causing error:
[https://imgur.com/pC3TpcU](url)

I am adding redux-debugger using RN version 0.67.3, Redux Toolkit version 1.8.0, React Redux version 7.2.6, and React Native Flipper version 0.137.0.

**Comment by plwai** [comment]
May I know the way you add the `createDebugger` part to RTK middleware?

**Comment by Isaacmeedinaa** [comment]
Yessir. 

```
import { configureStore } from "@reduxjs/toolkit";
import counterReducer from "../features/counter/counter-slice";

const createDebugger = require("redux-flipper").default;

export const store = configureStore({
  reducer: {
    counter: counterReducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(createDebugger),
});

export type AppDispatch = typeof store.dispatch;
export type RootState = ReturnType<typeof store.getState>;
```

I then export `store` and use it with React Redux provider:

```
const App: React.FC = () => {
  return (
    <Provider store={store}>
      <SafeAreaView style={styles.safeAreaView}>
        <StatusBar barStyle="default" />
        <View style={styles.container}>
          <Text>Hello World! Working with Redux-Toolkit</Text>
        </View>
      </SafeAreaView>
    </Provider>
  );
};
```

**Comment by Isaacmeedinaa** [comment]
Also, I wanted to mention that when adding redux-flipper as a middleware, it does not update the state of the counter state. I tested it with other middlewares like redux-logger and it updates the counter state accurately.

**Comment by plwai** [comment]
> @plwai Yessir.
> 
> ```
> import { configureStore } from "@reduxjs/toolkit";
> import counterReducer from "../features/counter/counter-slice";
> 
> const createDebugger = require("redux-flipper").default;
> 
> export const store = configureStore({
>   reducer: {
>     counter: counterReducer,
>   },
>   middleware: (getDefaultMiddleware) =>
>     getDefaultMiddleware().concat(createDebugger),
> });
> 
> export type AppDispatch = typeof store.dispatch;
> export type RootState = ReturnType<typeof store.getState>;
> ```
> 
> I then export `store` and use it with React Redux provider:
> 
> ```
> const App: React.FC = () => {
>   return (
>     <Provider store={store}>
>       <SafeAreaView style={styles.safeAreaView}>
>         <StatusBar barStyle="default" />
>         <View style={styles.container}>
>           <Text>Hello World! Working with Redux-Toolkit</Text>
>         </View>
>       </SafeAreaView>
>     </Provider>
>   );
> };
> ```

Hi @Isaacmeedinaa, it should be `createDebugger()` instead of `createDebugger`. This function do flipper connection initialization and return a function for middleware.

**Comment by Isaacmeedinaa** [comment]
Oh wow, yes. That makes total sense. It works now. Thank you!
