### ISSUE TITLE
Unreadable white coloring on hover while on dark mode

### ISSUE THREAD

**Issue by maharjanaman** [jk-gan/redux-flipper#66]
In dark mode, the diff and action are unreadable while hover over them,
<img width="366" alt="Screen Shot 2022-07-25 at 11 43 32" src="https://user-images.githubusercontent.com/14164484/180708630-4d2cb19e-7a79-4a63-a2c3-f26f65644fd0.png">
<img width="383" alt="Screen Shot 2022-07-25 at 11 47 23" src="https://user-images.githubusercontent.com/14164484/180708734-27d8fd44-bcf0-4596-b6fb-fd20308eaae0.png">

**Comment by ZeeshanAhmadKhalil** [comment]
Resolved in `0.158.0`

**Comment by maharjanaman** [comment]
Yeah, closing this out.
