### ISSUE TITLE
Add support for expo eas build

### ISSUE THREAD

**Issue by bleedingAyush** [jk-gan/redux-flipper#67]
Hey, I am developing my app in eas build, if you could add support for it. My development would become way easier. Thanks.

**Comment by plwai** [comment]
Hey. I don't really understand what is your problem. Can you please explain it?

**Comment by bleedingAyush** [comment]
I am developing my app in expo eas build. As expo doesn't support flipper directly. I had to use expo-community-flipper to make it work. If you could add support for eas build using their config plugins it would be great and I could debug my redux store with ease. Here is the [docs](https://docs.expo.dev/build/introduction/) for eas-build.

**Comment by plwai** [comment]
That is out of the scope of this plugin. This plugin is fully built on top of flipper. There is no way to run without flipper as the base. If you really wish to have such kind of plugins, it will be great if you can make it. 😄
